export const API_URL = "http://localhost:3000";

export const CLASSES = {
  INITIAL_DIV: "initial-div",
  CONTAINER: "container",
  TOP_DIV: "top-div",
  GAME_DIV: "game-div",
  FINDING_OPP_DIV: "finding-opponent-div",
  FINDING_OPP_BTN: "finding-opponent-button",
  DIFFIULTY_SEL: "difficulty-select",
  RESTART_BTN: "restart-button",
  OPP_STATS_DIV: "opponent-stats-div",
  OPP_PICTURE: "opponent-picture",
  OPP_NAME_LABEL: "opponent-name-label",
  OPP_DIFF_LABEL: "opponent-difficulty-label",
  YOUR_POINTS_DIV: "your-points-div",
  OPP_POINTS_DIV: "opponent-points-div",
  YOUR_POINTS: "your-points",
  OPP_POINTS: "opponent-points",
  YOUR_PICKS_DIV: "your-picks-div",
  OPP_PICKS_DIV: "opponent-picks-div",
  RESULT_DIV: "result-div",
  RESULT_FIGHTCARD_DIV: "result-fightcard-div",
  YOUR_FIGHTCARD_DIV: "your-fightcard-div",
  YOUR_FIGHT_DIV:"your-fight-div",
  YOUR_FIGHT_BLUE_DIV:"your-fight-blue-div",
  YOUR_FIGHT_RED_DIV:"your-fight-red-div",
  YOUR_FIGHT_PICK_DIV:"your-fight-pick-div",
  OPP_FIGHTCARD_DIV: "opponent-fightcard-div",
  ADD_PICK_BTN: "add-pick-button",
  PLAY_BTN: "play-button",
  NEW_PICK_DIV: "new-pick-div",
  WEIGHT_CLASS_SEL: "weightclass-select",
  BLUE_CORNER_SEL: "blue-corner-select",
  RED_CORNER_SEL: "red-corner-select",
  CORNER_SEL: "corner-select",
  TOP_NEW_PICK_DIV: "top-new-pick-div",
  BOTTOM_NEW_PICK_DIV: "bottom-new-pick-div",
  OUTCOME_DIV: "outcome-div",
  CORNER_RADIO: "corner-radio",
  METHOD_SEL: "method-select",
  ROUND_SEL: "round-select",
  RED_CORNER_DIV: "red-corner-div",
  BLUE_CORNER_DIV: "blue-corner-div",
  FIGHTER_STATS_DIV: "fighter-stats-div",
  STANDUP_LAB: "standup-label",
  GRAPPLING_LAB: "grappling-label",
  OVERALL_LAB: "overall-label",
};

export const INDEXES = {
  FIRST_SCORE: 0,
  SECOND_SCORE: 1,
  BLUE_CORNER: 0,
  RED_CORNER: 1,
  INITIAL_FIGHTER: 0,
};

export const INITIAL = {
  SCORE: 0,
};
